"""Provenance-scaled dual-run experiment — Modal entrypoint.

Runs the same CXR report through two independent VLM generators and
labels each (claim, image) pair with its provenance tier:
  SAME_MODEL   — claim generated by the same model that we're evaluating
  INDEPENDENT  — claim generated by a different model
  TRUSTED      — claim from a radiologist-authored reference (MS-CXR / OpenI)

For each tier, we compute verifier AUC and FPR@95TPR to quantify
how provenance-aware gating affects apparent performance.

Usage:
    modal run --detach v5/modal/run_provenance_scaled.py

Outputs (written to /data/v5/provenance_scaled/):
    pairs.json           — all (claim, image, gt_label, provenance_tier) records
    summary.json         — AUC / FPR@95 broken down by tier
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Literal

import modal

app = modal.App("claimguard-v5-provenance-scaled")

V5_IMAGE = (
    modal.Image.debian_slim(python_version="3.10")
    .pip_install(
        "torch==2.3.0",
        "transformers==4.41.0",
        "scikit-learn==1.4.2",
        "numpy",
        "tqdm",
        "pillow",
        "open_clip_torch",
        "datasets",
    )
    .run_commands("pip install huggingface_hub --upgrade")
)

volume = modal.Volume.from_name("claimguard-v5-data", create_if_missing=True)
DATA_ROOT = Path("/data/v5")
OUT_DIR = DATA_ROOT / "provenance_scaled"

ProvenanceTier = Literal["SAME_MODEL", "INDEPENDENT", "TRUSTED"]

# Generator pairs to run: (generator_A, generator_B)
# A generates report; B is the "independent" comparison model.
GENERATOR_PAIRS = [
    ("maira2", "medgemma"),
    ("chexagent", "llava_rad"),
]

# Models whose claims count as TRUSTED (radiologist-authored sources)
TRUSTED_SOURCES = {"ms_cxr", "openi"}


def _assign_provenance(
    claim_source: str,
    verifier_backbone: str,
) -> ProvenanceTier:
    if claim_source in TRUSTED_SOURCES:
        return "TRUSTED"
    if claim_source == verifier_backbone:
        return "SAME_MODEL"
    return "INDEPENDENT"


def _auc_and_fpr(scores: list[float], labels: list[int]) -> dict:
    """Compute AUC-ROC and FPR at 95% TPR."""
    from sklearn.metrics import roc_auc_score, roc_curve
    import numpy as np

    if len(set(labels)) < 2 or len(scores) < 2:
        return {"auc": None, "fpr_at_95tpr": None, "n": len(scores)}
    auc = float(roc_auc_score(labels, scores))
    fpr, tpr, _ = roc_curve(labels, scores)
    idx = np.searchsorted(tpr, 0.95)
    fpr95 = float(fpr[min(idx, len(fpr) - 1)])
    return {"auc": auc, "fpr_at_95tpr": fpr95, "n": len(scores)}


@app.function(
    image=V5_IMAGE,
    gpu="H100",
    timeout=3600 * 6,
    volumes={str(DATA_ROOT): volume},
    secrets=[
        modal.Secret.from_name("openai", required=False),
        modal.Secret.from_name("anthropic"),
        modal.Secret.from_name("huggingface-token"),
    ],
)
def run_provenance_experiment(verifier_backbone: str = "maira2") -> dict:
    """Score all pairs and compute per-tier metrics."""
    import torch

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Load GroundBench manifest (test split only)
    manifest_path = DATA_ROOT / "groundbench" / "groundbench_manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing {manifest_path} — run build_groundbench.py first.")

    with open(manifest_path) as f:
        all_rows = json.load(f)

    test_rows = [r for r in all_rows if r.get("split") == "test"]
    print(f"Test rows: {len(test_rows)}")

    # Load verifier checkpoint
    ckpt_path = DATA_ROOT / "checkpoints" / "v5_final.pt"
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Missing checkpoint {ckpt_path} — run train_v5.py first.")

    import sys
    sys.path.insert(0, str(DATA_ROOT.parent))
    from v5.model import V5Config, build_v5_model, build_v5_tokenizer

    device = "cuda" if torch.cuda.is_available() else "cpu"
    cfg = V5Config()
    tok = build_v5_tokenizer(cfg)
    model = build_v5_model(cfg)
    ckpt = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"], strict=False)
    model.to(device).eval()

    # Score each row
    from PIL import Image
    import torchvision.transforms as T

    transform = T.Compose([
        T.Resize((224, 224)),
        T.ToTensor(),
        T.Normalize(mean=[0.481, 0.458, 0.408], std=[0.269, 0.261, 0.276]),
    ])

    label2int = {"SUPPORTED": 0, "CONTRADICTED": 1}
    records = []

    for row in test_rows:
        claim_text = row.get("claim_text", "")
        gt_label = row.get("label", "")
        img_path = row.get("image_path", "")
        claim_source = row.get("generator", row.get("source", "unknown"))

        if gt_label not in label2int or not img_path or not Path(img_path).exists():
            continue

        provenance = _assign_provenance(claim_source, verifier_backbone)

        try:
            img = Image.open(img_path).convert("RGB")
            pv = transform(img).unsqueeze(0).to(device)
        except Exception:
            continue

        enc = tok(
            [claim_text],
            return_tensors="pt",
            padding="max_length",
            truncation=True,
            max_length=cfg.max_text_tokens,
        )
        with torch.no_grad():
            out = model(
                pv,
                enc["input_ids"].to(device),
                enc["attention_mask"].to(device),
            )
        import torch.nn.functional as F
        probs = F.softmax(out["verdict_logits"], dim=-1).cpu().numpy()[0]
        contradicted_score = float(probs[1])

        records.append({
            "claim_text": claim_text,
            "gt_label": gt_label,
            "gt_int": label2int[gt_label],
            "provenance_tier": provenance,
            "claim_source": claim_source,
            "contradicted_score": contradicted_score,
            "image_path": img_path,
        })

    pairs_path = OUT_DIR / "pairs.json"
    with open(pairs_path, "w") as f:
        json.dump(records, f, indent=2)
    print(f"Scored {len(records)} pairs → {pairs_path}")

    # Compute per-tier metrics
    from v5.eval.provenance_scaled import summarize_pairs
    summary = summarize_pairs(records)
    summary_path = OUT_DIR / "summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"Summary → {summary_path}")
    print(json.dumps(summary, indent=2))

    volume.commit()
    return summary


@app.local_entrypoint()
def main() -> None:
    result = run_provenance_experiment.remote(verifier_backbone="maira2")
    print(f"\nProvenance experiment complete:\n{json.dumps(result, indent=2)}")
